apiVersion: v1
kind: Service
metadata:
 name: todo-api-svc
 labels:
   app: todo-api-backend
spec:
 type: LoadBalancer
 selector:
   app: todo-api-backend
 ports:
 - port: 80
   targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: todo-api-backend-deployment
 labels:
   app: todo-api-backend
spec:
 replicas: 1
 selector:
   matchLabels:
     app: todo-api-backend
 template:
   metadata:
     labels:
       app: todo-api-backend
   spec:
     containers:
     - name: todo-api-backend
       image: <IMAGE_TAG>
       imagePullPolicy: Always
       ports:
       - containerPort: 8080
