kind: Service
apiVersion: v1
metadata:
  name: todo-react-svc
spec:
  type: LoadBalancer
  selector:
    app: todo-react-frontend
  ports:
    - port: 80
      targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-react-frontend
  template:
    metadata:
      labels:
        app: todo-react-frontend
    spec:
      containers:
        - name: todo-react-app
          image: <IMAGE_TAG>
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env: 
            - name: API_URL
              value: <API_URL>  # This is the URL of the backend service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m" 

