trigger:
- main

name: Deploy Bicep files

variables:
  - group: 'aca-vars'
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: azureServiceConnection
    value: 'internal_azure_subscription'
  - name: templateFile
    value: 'infra/main.bicep'
  - name: apiName
    value: 'todolist'
  - name: apiPort
    value: '8080'
  - name: mountPath
    value: '/etc/telegraf'
  - name: acrRepositoryName
    value: 'todo-api'

resources:
  containers:
  - container: mycontainer # name of the container (Alias) 
    image: todoApiImage # image name to be used in the pipeline
    type: ACR
    azureSubscription: $(azureServiceConnection)
    resourceGroup: $(resourceGroupName)
    registry: $(acrName)
    repository: $(acrRepositoryName)
    trigger:
      tags:
      - latest # tag for the container image to use

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  name: 'appDeployment'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
    deploymentOutputs: 'containerAppOutputs'
    overrideParameters: |
      -location $(location)
      -apiName: $(apiName)
      -apiPort: $(apiPort)
      -acrName: $(resources.container.mycontainer.registry)
      -grafanaPrincipalId: $(principalId)
      -containerImage: $(resources.container.mycontainer.repository):$(resources.container.mycontainer.tag)
      -userPrincipalId: $(principalId)
      -mountPath: $(mountPath)
