trigger:
- main

variables:
  - group: 'aca-vars'
  - name: acrName
    value: $[variables.acrName]
  - name: azureServiceConnection
    value: 'internal_azure_subscription'
  - name: imageRepository
    value: 'aca-todolist-demo-api'
  - name: tag
    value: '$(Build.BuildId)'
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
- stage: ContainerBuildStage
  displayName: Container build stage
  jobs:
  - job: ContainerBuildJob
    displayName: Container Build job
    pool:
      name: $(vmImageName)
    steps:
    - task: AzureCLI@2
      name: 'BuildAndPushImage'
      displayName: 'Build and push an image to Azure Container Registry'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        inlineScript: |
          az acr build --registry $(acrName) --platform linux --file /api/Dockerfile --image $(imageRepository):$(tag) /api
        scriptLocation: inlineScript
