trigger:
  branches:
    include:
      - 'main'
  paths:
    include:
      - 'infra/*'

name: 'Deploy Infrastructure'

variables:
  - group: 'aca-vars'
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: location
    value: 'australiaeast'
  - name: locationShortName
    value: 'aue'
  - name: resourceGroupName
    value: 'aca-todolist-$(locationShortName)-rg'
  - name: azureServiceConnection
    value: 'internal_azure_subscription'
  - name: templateFilePath
    value: 'infra/main.bicep'
  - name: fileShareName
    value: 'telegraf-share'
  - name: orgName
    value: 'kainidev'
  - name: projectName
    value: 'AzureFastTrackCustomerExamples'
  - name: group-id
    value: '17'


pool:
  vmImage: $(vmImageName)

steps:
- checkout: self 

- task: AzureResourceManagerTemplateDeployment@3
  name: 'infraDeployment'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(azureServiceConnection)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: $(templateFilePath)
    deploymentMode: 'Incremental'
    deploymentName: 'infra'
    deploymentOutputs: 'infraOutputs'
    overrideParameters: '-location $(location) -fileShareName $(fileShareName)'

- bash: |
    echo "##vso[task.setvariable variable=containerAppEnvironmentId]$(echo $INFRA_OUTPUTS | jq -r '.containerAppEnvironmentId.value')"
    echo "##vso[task.setvariable variable=acrName]$(echo $INFRA_OUTPUTS | jq -r '.acrName.value')"
    echo "##vso[task.setvariable variable=sqlCxnString]$(echo $INFRA_OUTPUTS | jq -r '.sqlCxnString.value')"
    echo "##vso[task.setvariable variable=storageAccountName]$(echo $INFRA_OUTPUTS | jq -r '.storageAccountName.value')"
    echo "##vso[task.setvariable variable=sqlServerName]$(echo $INFRA_OUTPUTS | jq -r '.sqlServerName.value')"

  displayName: 'Parse ARM outputs'
  env:
    INFRA_OUTPUTS: $(infraOutputs)

- script: |
    echo $SYSTEM_ACCESSTOKEN | az devops login

    az pipelines variable-group variable update \
      --group-id $(group-id) \
      --name containerAppEnvironmentId \
      --value "$(containerAppEnvironmentId)" \
      --org https://dev.azure.com/$(orgName) \
      --project $(projectName)

      az pipelines variable-group variable update \
      --group-id $(group-id) \
      --name acrName \
      --value "$(acrName)" \
      --org https://dev.azure.com/$(orgName) \
      --project $(projectName)

      az pipelines variable-group variable update \
      --group-id $(group-id) \
      --name sqlCxnString \
      --value "$(sqlCxnString)" \
      --org https://dev.azure.com/$(orgName) \
      --project $(projectName)

      az pipelines variable-group variable update \
      --group-id $(group-id) \
      --name storageAccountName \
      --value "$(storageAccountName)" \
      --org https://dev.azure.com/$(orgName) \
      --project $(projectName)

      az pipelines variable-group variable update \
      --group-id $(group-id) \
      --name sqlServerName \
      --value "$(sqlServerName)" \
      --org https://dev.azure.com/$(orgName) \
      --project $(projectName)

  displayName: "Update variables inside 'acr-vars' variable group"
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
