trigger:
  branches:
    include:
      - 'main'
  paths:
    include:
      - 'infra/*'

name: 'Deploy Infrastructure'

variables:
  vmImageName: 'ubuntu-latest'
  location: 'australiaeast'
  locationShortName: 'aue'
  resourceGroupName: 'aca-todolist-$(locationShortName)-rg'
  azureServiceConnection: 'internal_azure_subscription'
  templateFilePath: 'infra/main.bicep'
  fileShareName: 'telegraf-share'

pool:
  vmImage: $(vmImageName)

steps:
- checkout: self 

- task: AzureResourceManagerTemplateDeployment@3
  name: 'infraDeployment'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(azureServiceConnection)
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: $(templateFilePath)
    deploymentMode: 'Incremental'
    deploymentName: 'infraDeployment'
    deploymentOutputs: 'infraOutputs'
    overrideParameters: |
      -location $(location)
      -fileShareName: $(fileShareName)
      -grafanaPrincipalId: $(userPrincipalId)
