{
 "title": "TodoList Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Go Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Telegraf/go_memstats_alloc_bytes",
      "dimensionFilters": [
       {
        "dimension": "host",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "gauge",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "todolist-cbellee-rg",
      "resourceName": "todolist-cbellee",
      "timeGrain": "auto"
     },
     "subscription": "b2375b5f-8dab-4436-b87c-32bc7fdce5d0",
     "subscriptions": [
      "b2375b5f-8dab-4436-b87c-32bc7fdce5d0"
     ]
    }
   ]
  },
  {
   "title": "Go Virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Telegraf/process_virtual_memory_bytes",
      "dimensionFilters": [
       {
        "dimension": "host",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "gauge",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "todolist-cbellee-rg",
      "resourceName": "todolist-cbellee",
      "timeGrain": "auto"
     },
     "subscription": "b2375b5f-8dab-4436-b87c-32bc7fdce5d0",
     "subscriptions": [
      "b2375b5f-8dab-4436-b87c-32bc7fdce5d0"
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.app/containerapps",
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "UsageNanoCores",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "todolist-cbellee-rg",
      "resourceName": "todolist-cbellee",
      "timeGrain": "auto"
     },
     "subscription": "b2375b5f-8dab-4436-b87c-32bc7fdce5d0"
    }
   ]
  },
  {
   "title": "Database wait count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Telegraf/gorm_dbstats_wait_count",
      "dimensionFilters": [
       { "dimension": "db_name", "filters": [ "sqlserver" ], "operator": "eq" },
       {
        "dimension": "host",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "gauge",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "todolist-cbellee-rg",
      "resourceName": "todolist-cbellee",
      "timeGrain": "auto"
     },
     "subscription": "b2375b5f-8dab-4436-b87c-32bc7fdce5d0"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Replica Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.app/containerapps",
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "todolist-cbellee-rg",
      "resourceName": "todolist-cbellee",
      "timeGrain": "auto"
     },
     "subscription": "b2375b5f-8dab-4436-b87c-32bc7fdce5d0"
    }
   ]
  },
  {
   "title": "HTTP Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Telegraf/todoapi_http_duration_seconds",
      "dimensionFilters": [
       {
        "dimension": "host",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "count",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "todolist-cbellee-rg",
      "resourceName": "todolist-cbellee",
      "timeGrain": "auto"
     },
     "subscription": "b2375b5f-8dab-4436-b87c-32bc7fdce5d0"
    }
   ]
  }
 ]
}